#!/usr/bin/env bash

set -euxo pipefail

# The version of the npm package generated by the `output` stage of the
# Dockerfile. It is used for the `version` field of its `package.json` and for
# the name of the generated archive (`onlyoffice-x2t-<version>.tgz`).
if [ $# -lt 1 ]; then
  echo "usage: $0 <release_version> [docker-build-option]..." >&2
  echo "for example: $0 1.2.3" >&2
  exit 1
fi
release_version="$1"
shift

# 1. Compile the project with docker

rm -rf results build

if command -v docker >/dev/null 2>&1; then
  builder=(docker build)
elif command -v podman >/dev/null 2>&1; then
  # Dockerfile contains a SHELL command needed across multi-stage images (required
  # by `. /emsdk/emsdk_env.sh`), however this is not part of the standard OCI format.
  # see: https://github.com/podman-container-tools/buildah/issues/6460
  builder=(podman build --format docker)
else
  echo "error: neither docker nor podman is available" >&2
  exit 127
fi

"${builder[@]}" "$@" --target test-output -o results .
mkdir build
"${builder[@]}" "$@" --build-arg release_version="$release_version" --target output -o build/docker .

# 2. Generate the final npm package

mkdir build/npm-package-content
cp build/docker/x2t.js build/npm-package-content
cp build/docker/x2t.wasm build/npm-package-content
printf '%s\n' \
  '{' \
  '  "name": "onlyoffice-x2t",' \
  "  \"version\": \"$release_version\"," \
  '  "description": "OnlyOffice x2t file converter compiled to WebAssembly",' \
  '  "main": "x2t.js",' \
  '  "license": "AGPL-3.0-or-later",' \
  '  "private": true,' \
  '  "files": ["x2t.js", "x2t.wasm"]' \
  '}' > build/npm-package-content/package.json
cd build/npm-package-content
package_archive="$(npm pack --ignore-scripts --silent --pack-destination ..)"
cd ..
sha512sum "$package_archive" > "$package_archive.sha512"
